//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doomtrain.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doomtrain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a None
        ///Physical Attack
        ///Magic Attack
        ///Curative Magic
        ///Curative Item
        ///Revive
        ///Revive At Full HP
        ///% Physical Damage
        ///% Magic Damage
        ///Renzokuken Finisher
        ///Squall Gunblade Attack
        ///GF
        ///Scan
        ///LV Down
        ///Summon Item?
        ///GF (Ignore Target SPR)
        ///LV Up
        ///Card
        ///Kamikaze
        ///Devour
        ///% GF Damage
        ///Unknown 1
        ///Magic Attack (Ignore Target SPR)
        ///Angelo Search
        ///Moogle Dance
        ///White Wind (Quistis)
        ///LV? Attack
        ///Fixed Damage
        ///Target Current HP - 1
        ///Fixed Magic Damage Based on GF Level
        ///Unknown 2
        ///Unknown 3
        ///Give Percentage HP
        ///Unknown 4
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string Attack_Type_List {
            get {
                return ResourceManager.GetString("Attack_Type_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletetooltip {
            get {
                object obj = ResourceManager.GetObject("deletetooltip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doomtrain {
            get {
                object obj = ResourceManager.GetObject("doomtrain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doomtrainbig {
            get {
                object obj = ResourceManager.GetObject("doomtrainbig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] labelDoomtrain {
            get {
                object obj = ResourceManager.GetObject("labelDoomtrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 000 - None
        ///001 - Cure
        ///002 - Fire
        ///003 - Thunder
        ///004 - Double
        ///005 - Phoenix Down
        ///006 - Leviathan Summon (Tsunami)
        ///007 - Mega Phoenix
        ///008 - Doom
        ///009 - Doom Activation
        ///010 - Ray-Bomb
        ///011 - Storm Breath
        ///012 - Blade Shot
        ///013 - Dark Mist/Poison Mist
        ///014 - Death/Death Stone
        ///015 - Draw
        ///016 - Recover
        ///017 - Elvoret Entrance
        ///018 - Elvoret Death
        ///019 - Raldo Ball
        ///020 - NORG Pod Opening
        ///021 - Triple
        ///022 - Bio
        ///023 - Psycho Blast
        ///024 - Esuna
        ///025 - Cura
        ///026 - Clash
        ///027 - Full-Life
        ///028 - Curaga
        ///02 [stringa troncata]&quot;;.
        /// </summary>
        internal static string Magic_ID_List {
            get {
                return ResourceManager.GetString("Magic_ID_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] mainTabFont {
            get {
                object obj = ResourceManager.GetObject("mainTabFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveas {
            get {
                object obj = ResourceManager.GetObject("saveas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tooltip {
            get {
                object obj = ResourceManager.GetObject("tooltip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
